apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
      version: blue
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: django-app
        version: blue
    spec:
      containers:
        - name: django-container
          image: your-django-image:2.0   # Updated image version
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
