pipeline {
    agent any

    environment {
        VENV = 'venv'
        DOCKER_IMAGE = 'your-dockerhub-username/messaging_app:latest'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Antwi-tech/alx-backend-python.git',
                    credentialsId: 'github-creds'
            }
        }

    stage('Setup Python Environment') {
        steps {
            script {
                sh """
                python3 -m venv ${VENV}
                source ${VENV}/bin/activate
                pip3 install --upgrade pip
                pip3 install -r messaging_app/requirements.txt
                """
        }
    }
}


        stage('Run Tests') {
            steps {
                sh """
                source ${VENV}/bin/activate
                pytest messaging_app/tests/ --junitxml=report.xml
                """
            }
        }

        stage('Publish Report') {
            steps {
                junit 'report.xml'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh """
                    docker build -t ${DOCKER_IMAGE} messaging_app/
                    """
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds',
                                                 usernameVariable: 'DOCKER_USER',
                                                 passwordVariable: 'DOCKER_PASS')]) {
                    sh """
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    docker push ${DOCKER_IMAGE}
                    """
                }
            }
        }
    }

    triggers {
        // Manual trigger only
    }
}
